server:
  port: 8080

spring:
  application:
    name: token-management-v1
  data:
    redis:
      host: ${REDIS_DOMAIN:localhost}
      port: 6379
      timeout: 2500
  cache:
    type: redis #enable cache

configuration:
  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  cache:
    tokens:
      time-to-live: MINUTE
      key-prefix: poc.tokens

  selector-class:
    token-cache-helper: com.demo.service.entrypoint.management.helper.TokenCacheHelperV2

  rest-clients:
    web-security-v1:
      request:
        endpoint: ${WEB_AUTH_V1_ENDPOINT:http://localhost:8082/poc/web/security/v1/token}
        headers:
          provided:
            Authorization: ${WEB_AUTH_V1_HEADER_BASIC_AUTH:Basic d2ViLXVzZXI6d2ViLXBhc3N3b3Jk}
            Ocp-Subscription-Key: ${WEB_AUTH_V1_HEADER_SUBSCRIPTION_KEY:dummy-web-subscription-key}
            Content-Type: application/x-www-form-urlencoded
          forwarded:
            channelId: channelId
          auto-generated:
            timestamp: TIMESTAMP
          tracing:
            traceParent: TRACE_PARENT
        form-data:
          grant_type: client_credentials
          scope: all
      performance:
        timeout: GOOD
        concurrency: MEDIUM

    app-security-v1:
      request:
        endpoint: ${APP_AUTH_V1_ENDPOINT:http://localhost:8082/poc/app/security/v1/token}
        headers:
          provided:
            Authorization: ${APP_AUTH_V1_HEADER_BASIC_AUTH:Basic YXBwLXVzZXI6YXBwLXBhc3N3b3Jk}
            Ocp-Subscription-Key: ${APP_AUTH_V1_HEADER_SUBSCRIPTION_KEY:dummy-app-subscription-key}
            Content-Type: application/x-www-form-urlencoded
          forwarded:
            channelId: channelId
          auto-generated:
            timestamp: TIMESTAMP
          tracing:
            traceParent: TRACE_PARENT
        form-data:
          grant_type: client_credentials
          scope: all
      performance:
        timeout: GOOD
        concurrency: MEDIUM

# actuator endpoints
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always
      probes: #livess & readiness probe
        enabled: true